version: "3"
services:
  docs:
    restart: always
    build:
      context: ../
      dockerfile: ./ci/Dockerfile
    working_dir: /usr/share/nginx/html
    stdin_open: true
    ports:
      - '${DOCKER_PORT}:80'
  server:
    restart: always
    build:
      context: ../
      dockerfile: ../ci/Server.Dockerfile
    ports:
      - '${SRV_PORT}:9090'
